---
# groups.yaml file
# Each group is used to attribute back to a platform
ios:
    platform: ios
    # Setting scrapli connection options
    # https://github.com/carlmontanari/nornir_scrapli#a-simple-example
    connection_options:
        scrapli:
            platform: cisco_iosxe
            port: 22
            extras:
                auth_strict_key: false

junos:
    platform: junos
    # Setting scrapli connection options
    # https://github.com/carlmontanari/nornir_scrapli#a-simple-example
    connection_options:
        scrapli:
            platform: juniper_junos
            port: 22
            extras:
                auth_strict_key: false


eos:
    platform: eos
    # Setting scrapli connection options
    # https://github.com/carlmontanari/nornir_scrapli#a-simple-example
    connection_options:
        scrapli:
            platform: arista_eos
            port: 22
            extras:
                auth_strict_key: false

nxos:
    platform: nxos
    # Setting scrapli connection options
    # https://github.com/carlmontanari/nornir_scrapli#a-simple-example
    connection_options:
        scrapli:
            platform: cisco_nxos
            port: 22
            extras:
                auth_strict_key: false
