name: net-api-docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag writememe/net-api:$(date +%s)
    - name: Run the Docker image
      run: 	docker run -d --env-file=.env-vars -p 5000:5000 writememe/net-api:$(date +%s)
      
